### ISSUE TITLE
add small examples for each exported function

### ISSUE THREAD

**Issue by courtiol** [radchukv/adRes#3]
It would be good to have small examples for the exported function for both the users and us.
For the user, it helps to understand the output of each function.
For us, it helps to modify the code and yet make sure the output are not changing.
Ideally, those examples should not have to use many functions, they should be as minimal as possible.

**Comment by radchukv** [comment]
Yes, we'll do that. Initially I was thinking of adding examples in the end, once everything works well together. But you are probably right and we should do it for each function right away, as part of the development process.

**Comment by courtiol** [comment]
done by @radchukv
